export const products = [
    { id: 1, name: 'Beach Ball', price: 2.99, sku: 'BCHBLL', stock: 100 },
    { id: 2, name: 'Sunscreen SPF 50', price: 9.99, sku: 'SUNSC50', stock: 50 },
    { id: 3, name: 'Flip Flops', price: 12.99, sku: 'FLPFLP', stock: 75 },
    { id: 4, name: 'Beach Towel', price: 14.99, sku: 'BCHTWL', stock: 60 },
    { id: 5, name: 'Sunglasses', price: 19.99, sku: 'SNGLSS', stock: 80 },
    { id: 6, name: 'Cooler Bag', price: 24.99, sku: 'CLRBAG', stock: 40 },
    { id: 7, name: 'Sand Bucket Set', price: 7.99, sku: 'SNDBCKT', stock: 90 },
    { id: 8, name: 'Swim Goggles', price: 15.99, sku: 'SWMGGLS', stock: 55 },
    { id: 9, name: 'Waterproof Phone Case', price: 11.99, sku: 'WTRPHCSE', stock: 65 },
    { id: 10, name: 'Portable Beach Umbrella', price: 29.99, sku: 'BCHUMBR', stock: 30 },
    { id: 11, name: 'Picnic Blanket', price: 17.99, sku: 'PCNCBLKT', stock: 50 },
    { id: 12, name: 'Insulated Water Bottle', price: 21.99, sku: 'INSWB', stock: 45 },
    { id: 13, name: 'Beach Chair', price: 39.99, sku: 'BCHCHR', stock: 25 },
    { id: 14, name: 'Snorkel Set', price: 27.99, sku: 'SNKLSET', stock: 35 },
    { id: 15, name: 'Floating Pool Lounge', price: 34.99, sku: 'FLTPNL', stock: 20 },
    { id: 16, name: 'Beach Frisbee', price: 5.99, sku: 'BCHFRSB', stock: 85 },
    { id: 17, name: 'Swim Shorts', price: 22.99, sku: 'SWMSHRT', stock: 70 },
    { id: 18, name: 'Inflatable Ring', price: 9.49, sku: 'INFTRNG', stock: 95 },
    { id: 19, name: 'Pool Noodle', price: 6.99, sku: 'PLNDL', stock: 100 },
    { id: 20, name: 'Waterproof Speaker', price: 49.99, sku: 'WTRSPK', stock: 25 },
    { id: 21, name: 'Beach Volleyball', price: 18.99, sku: 'BCHVLBL', stock: 40 },
    { id: 22, name: 'Underwater Camera', price: 89.99, sku: 'UNDWCAM', stock: 15 },
    { id: 23, name: 'Surfboard Wax', price: 4.99, sku: 'SFBWAX', stock: 120 },
    { id: 24, name: 'Mesh Beach Bag', price: 13.99, sku: 'MSHBCHBG', stock: 55 },
    { id: 25, name: 'Kite', price: 16.99, sku: 'KITE001', stock: 45 },
    { id: 26, name: 'Floating Cooler', price: 54.99, sku: 'FLTCOL', stock: 20 },
    { id: 27, name: 'Swim Cap', price: 8.99, sku: 'SWMCP', stock: 60 },
    { id: 28, name: 'Bodyboard', price: 49.99, sku: 'BDYBRD', stock: 30 },
    { id: 29, name: 'Swim Arm Bands', price: 7.49, sku: 'SWMARM', stock: 90 },
    { id: 30, name: 'Beach Hat', price: 19.99, sku: 'BCHHT', stock: 70 },
    { id: 31, name: 'Swim Ring for Kids', price: 12.49, sku: 'SWMRNGK', stock: 80 },
    { id: 32, name: 'Diving Fins', price: 39.99, sku: 'DIVFNS', stock: 35 },
    { id: 33, name: 'Tote Bag', price: 24.99, sku: 'TOTEBG', stock: 50 },
    { id: 34, name: 'Inflatable Canoe', price: 199.99, sku: 'INFLCAN', stock: 10 },
    { id: 35, name: 'Waterproof Picnic Mat', price: 14.99, sku: 'WTPMAT', stock: 55 },
    { id: 36, name: 'Portable Fan', price: 29.99, sku: 'PORTFAN', stock: 40 },
    { id: 37, name: 'Water Shoes', price: 34.99, sku: 'WTRSHO', stock: 50 },
    { id: 38, name: 'Beach Wagon', price: 79.99, sku: 'BCHWGN', stock: 20 },
    { id: 39, name: 'Beach Cover-up', price: 27.99, sku: 'BCHCVRP', stock: 45 },
    { id: 40, name: 'UV Protection Shirt', price: 32.99, sku: 'UVSHRT', stock: 50 },
    { id: 41, name: 'Boogie Board', price: 44.99, sku: 'BOGIBRD', stock: 25 },
    { id: 42, name: 'Sand-Free Towel', price: 18.99, sku: 'SNDTWL', stock: 60 },
    { id: 43, name: 'Portable Grill', price: 59.99, sku: 'PORTGRL', stock: 15 },
    { id: 44, name: 'Beach Tent', price: 99.99, sku: 'BCHTENT', stock: 12 },
    { id: 45, name: 'Kayak Paddle', price: 69.99, sku: 'KYKPDDL', stock: 18 },
    { id: 46, name: 'Floating Lounge Chair', price: 49.99, sku: 'FLTCHIR', stock: 20 },
    { id: 47, name: 'Waterproof Backpack', price: 39.99, sku: 'WTPBCKP', stock: 30 },
    { id: 48, name: 'Beach Paddle Ball Set', price: 14.99, sku: 'BCHPDBL', stock: 50 },
    { id: 49, name: 'Surfboard Leash', price: 22.99, sku: 'SFBLESH', stock: 40 },
    { id: 50, name: 'Hydration Pack', price: 34.99, sku: 'HYDPAK', stock: 30 },
    { id: 51, name: 'Pool Float', price: 24.99, sku: 'PLFLT', stock: 40 },
    { id: 52, name: 'Bamboo Mat', price: 19.99, sku: 'BMBMAT', stock: 55 },
    { id: 53, name: 'Ocean Life Book', price: 14.99, sku: 'OCLBOOK', stock: 35 },
    { id: 54, name: 'Portable Hammock', price: 49.99, sku: 'PORTHMK', stock: 20 },
    { id: 55, name: 'Kids Beach Chair', price: 29.99, sku: 'KDSBCHR', stock: 30 },
    { id: 56, name: 'Waterproof Pouch', price: 9.99, sku: 'WTPPCH', stock: 75 },
    { id: 57, name: 'Beach Tote with Cooler', price: 34.99, sku: 'BCHTCLC', stock: 25 },
    { id: 58, name: 'Floating Beer Pong Table', price: 49.99, sku: 'FLTBNGP', stock: 15 },
    { id: 59, name: 'Beach Hand Fan', price: 8.99, sku: 'BCHHDFN', stock: 60 }
  ];
  
  